apiVersion: v1
kind: PersistentVolume
metadata:
  name: webook-mysql-pv
spec:
    storageClassName: record
    capacity:
      storage: 1Gi
    accessModes:
      - ReadWriteOnce
    hostPath:
      path: "/mnt/data"

  